export default {
  counties: [
    'Berlin',
    'Hamburg',
    'München',
    'Köln',
    'Frankfurt am Main',
    'Essen',
    'Dortmund',
    'Stuttgart',
    'Düsseldorf',
    'Bremen',
    'Hannover',
    'Duisburg',
    'Leipzig',
    'Nürnberg',
    'Dresden',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Manheim',
    'Bonn',
    'Rostock',
  ],
};
